name: version3
description: "Smart Home IoT Controller with ESP32 and MQTT"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  lottie: ^3.1.0
  flutter_animate: ^4.5.0
  
  # State Management
  provider: ^6.1.2
  
  # MQTT
  mqtt_client: ^10.2.1
  
  # Local Storage
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  path: ^1.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Charts & Visualization
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^26.2.4
  syncfusion_flutter_gauges: ^26.2.4
  
  # Notifications
  flutter_local_notifications: ^17.2.1+2
  
  # UI Enhancements
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  glassmorphism: ^3.0.0
  card_swiper: ^3.0.1
  carousel_slider: ^5.0.0
  dotted_border: ^2.1.0
  
  # 🎨 Image Picker for Device Avatars
  image_picker: ^1.2.0
  
  # Icons
  font_awesome_flutter: ^10.7.0
  line_icons: ^2.0.3
  
  # Navigation
  go_router: ^14.2.0
  
  # Utils
  intl: ^0.19.0
  timeago: ^3.7.0
  dio: ^5.5.0+1
  
  # Authentication & Firestore
  google_sign_in: ^6.1.0
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.3
  connectivity_plus: ^7.0.0
  permission_handler: ^12.0.1
  
  # Animations
  rive: ^0.13.7
  flutter_animation_progress_bar: ^2.3.1
  
  # Date & Time
  flutter_datetime_picker_plus: ^2.2.0
  
  # JSON
  json_annotation: ^4.9.0
  
  # Others
  url_launcher: ^6.3.0
  share_plus: ^10.0.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # Assets - CHỈ DÙNG LOTTIE ANIMATIONS (OPTIONAL)
  # assets:
  #   - assets/animations/