// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYxPNmY7tlabmbnQeLZVyBpzjvMliovRM',
    appId: '1:1024906096119:web:25a32deb41ac0ceb0f92f2',
    messagingSenderId: '1024906096119',
    projectId: 'iot-smart-home-3589f',
    authDomain: 'iot-smart-home-3589f.firebaseapp.com',
    storageBucket: 'iot-smart-home-3589f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_iBHiD3O-NC96s4Wy1mQ78L8hguG_o0U',
    appId: '1:1024906096119:android:98f4d8449aa0cfa10f92f2',
    messagingSenderId: '1024906096119',
    projectId: 'iot-smart-home-3589f',
    storageBucket: 'iot-smart-home-3589f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKcaMos5gCC-jcRUKZSZd1RlSZGoWsFOg',
    appId: '1:1024906096119:ios:0f460a879e47b01b0f92f2',
    messagingSenderId: '1024906096119',
    projectId: 'iot-smart-home-3589f',
    storageBucket: 'iot-smart-home-3589f.firebasestorage.app',
    androidClientId: '1024906096119-m8gignagmk1id4q3qth9r29ormfveumh.apps.googleusercontent.com',
    iosClientId: '1024906096119-h4374lkmrgjdovlgmke6t2qr79ltrdom.apps.googleusercontent.com',
    iosBundleId: 'com.example.version3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKcaMos5gCC-jcRUKZSZd1RlSZGoWsFOg',
    appId: '1:1024906096119:ios:0f460a879e47b01b0f92f2',
    messagingSenderId: '1024906096119',
    projectId: 'iot-smart-home-3589f',
    storageBucket: 'iot-smart-home-3589f.firebasestorage.app',
    androidClientId: '1024906096119-m8gignagmk1id4q3qth9r29ormfveumh.apps.googleusercontent.com',
    iosClientId: '1024906096119-h4374lkmrgjdovlgmke6t2qr79ltrdom.apps.googleusercontent.com',
    iosBundleId: 'com.example.version3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYxPNmY7tlabmbnQeLZVyBpzjvMliovRM',
    appId: '1:1024906096119:web:341de68f4d2fd2710f92f2',
    messagingSenderId: '1024906096119',
    projectId: 'iot-smart-home-3589f',
    authDomain: 'iot-smart-home-3589f.firebaseapp.com',
    storageBucket: 'iot-smart-home-3589f.firebasestorage.app',
  );
}
